services:
  analytics:
    build: 
      context: analytics
      dockerfile: Dockerfile
    container_name: analytics
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      - ./queries:/queries
    working_dir: /data  # Change to a mounted volume directory
    command: ["sleep", "infinity"]  # Keep the container running
    environment:
      PYTHONUNBUFFERED: 1

  # Autres services (Dask, Spark, ClickHouse, etc.)
  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    ports:
      - "8786:8786"  # Scheduler port
      - "8787:8787"  # Dashboard port
    command: ["dask-scheduler"]

  dask-worker:
    image: daskdev/dask:latest
    container_name: dask-worker
    depends_on:
      - dask-scheduler
    command: ["dask-worker", "dask-scheduler:8786"]

  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark Master
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  spark-worker:
    image: bitnami/spark:3.3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client
    volumes:
      - ./data:/var/lib/clickhouse
    restart: always
